version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: itechart-mongo
    ports: 
      - 27017:27017
    volumes: 
      - ~/mongo-volume:/data/db
  postgres:
    image: postgres:latest
    container_name: itechart-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ~/postgres-volume:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8001:8080/tcp
    environment: 
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    tty: true